version: "3"

networks:
    web:
services:
    traefik:
        image: traefik:v2.3
        ports:
            - 80:80
            - 8080:8080
        restart: always
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - $PWD/traefik.yml:/traefik.yml
            - $PWD/traefik_dynamic.yml:/traefik_dynamic.yml
        networks:
            - web
