http:
  middlewares:
    simpleAuth:
      basicAuth:
        users:
          - 'admin:$apr1$1L1v3.Lx$mh9BpyRB6cfRjItG4lqCn0'
  routers:
    api:
      rule: Host(`monitor.localhost`)
      entrypoints:
        - web
      middlewares:
        - simpleAuth
      service: api@internal
      tls:
        certResolver: lets-encrypt
