[http.middlewares.simpleAuth.basicAuth]
  users = [
	"admin:$apr1$1L1v3.Lx$mh9BpyRB6cfRjItG4lqCn0"
  ]

[http.routers.api]
  rule = "Host(`monitor.haidousm.com`)"
  entrypoints = ["websecure"]
  middlewares = ["simpleAuth"]
  service = "api@internal"
  [http.routers.api.tls]
    certResolver = "lets-encrypt"
