version: "3"

networks:
    web:
        external: true
    internal:
        external: false

services:
    traefik:
            image: traefik:v2.3
            ports:
                - 80:80
                - 443:443
            restart: always
            volumes:
                - /var/run/docker.sock:/var/run/docker.sock
                - $PWD/traefik.toml:/traefik.toml
                - $PWD/traefik_dynamic.toml:/traefik_dynamic.toml
                - $PWD/acme.json:/acme.json
            networks:
                - web
    traefikker:
            image: haidousm/traefikker:1.0.0
            ports:
                - 6969:8080
            restart: always
            volumes:
                - $PWD/../docker-compose.yml:/usr/src/docker-config/docker-compose.yaml
                - /var/run/docker.sock:/var/run/docker.sock
            networks:
                - web
