version: "3"

networks:
    web:
        external: true
    internal:
        external: false

services:
    traefik:
            image: traefik:v2.3
            ports:
                - 80:80
                - 443:443
            restart: always
            volumes:
                - /var/run/docker.sock:/var/run/docker.sock
                - $PWD/traefik.toml:/traefik.toml
                - $PWD/traefik_dynamic.toml:/traefik_dynamic.toml
                - $PWD/acme.json:/acme.json
            networks:
                - web
    traefiker:
            image: haidousm/traefiker:1.0.0
            restart: always
            ports:
                - 8080:8080
            volumes:
                - $PWD/../docker-compose.yml:/usr/src/app/docker-compose.yml
                - /var/run/docker.sock:/var/run/docker.sock
            labels:
                - traefik.http.routers.traefiker.rule=Host(`admin.moussa.codes`)
                - traefik.http.routers.traefiker.tls=true
                - traefik.http.routers.traefiker.tls.certresolver=lets-encrypt
            networks:
                - web
